language: node_js
node_js:
  - "iojs"
  - "lts/*"
  - "0.10"
  - "0.11"
  - "0.12"
  - "4"
  - "5"
  - "6"
  - "7"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
services:
  - redis-server
