pipeline {
    agent none

    stages {
        stage('Install and Test Filter') {
            agent {
                docker 'node:8.12.0-alpine'
            }
            environment {
                CI = 'true'
            }
            stages{
                stage('Install') {
                    dir('./microservices/Filter/modules/base/') {
                        steps {
                            sh 'npm install --only=dev'
                        }
                    }
                }
                stage('Test') {
                    dir('./microservices/Filter/modules/base/') {
                        steps {
                            sh 'npm test'
                        }
                    }
                }
            }
        }

        stage('Build Filter Microservice') {
            agent {
                dockerfile {
                  filename 'Dockerfile'
                  dir './microservices/Filter/modules/base/docker/1.0'
                  additionalBuildArgs '-t curiousben/filter:v2.0'
                }
            }
            steps {
                sh "echo Done"
            }
        }
    }
}
