pipeline {
    agent none

    environment {
      microservicePath = './microservices/Filter/modules/base/'
      version = '1.0'
    }

    stages {
        stage('Install and Test Filter') {
            agent {
                docker 'node:8.12.0-jessie'
                customWorkspace microservicePath
            }
            environment {
                CI = 'true'
            }
            stages{
                stage('Install') {
                    steps {
                        sh 'npm install --only=dev'
                    }
                }
                stage("Test") {
                    steps {
                        sh 'npm test'
                    }
                }
            }
        }

        stage('Build Filter Microservice') {
            agent {
                node {
                    customWorkspace microservicePath
                }
            }
            steps {
                sh './buildCoreJS.sh ${version}'
            }
        }
        stage('Build Docker Image') {
            agent {
                dockerfile {
                  filename 'Dockerfile'
                  dir './microservices/Filter/modules/base/docker/1.0'
                  additionalBuildArgs '-t curiousben/filter:v2.0'
                }
            }
            steps {
                sh "echo Done"
            }
        }
    }
}
